[package]
name = "dx-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
serde_yaml.workspace = true
thiserror.workspace = true
anyhow.workspace = true
once_cell.workspace = true
tracing.workspace = true
