[package]
name = "dx-tui"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
ratatui.workspace = true
crossterm.workspace = true
tokio.workspace = true
tracing.workspace = true
